export const FETCH_POST = "FETCH_POST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const EDIT_POST_BY_ID = "EDIT_POST_BY_ID";
export const EDIT_POST_BY_ID_SUCCESS = "EDIT_POST_BY_ID_SUCCESS";
export const ADD_POST ="ADD_POST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const FETCH_POST_BY_ID = "FETCH_POST_BY_ID";
export const FETCH_POST_BY_ID_SUCCESS = "FETCH_POST_BY_ID_SUCCESS";